[package]
name = "jsondiff"
version = "3.0.0"
edition = "2021"

[dependencies]
clap = "4.5.7"
console = "0.15.8"
crossterm = "0.27.0"
difference = "2.0.0"
serde_json = "1.0.117"
termcolor = "1.4.1"
tui = "0.19.0"
